version: "3"

services:
  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
      - 27018:27017
    volumes:
      - ./_docker/apibara_mongodb:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_BASICAUTH_USERNAME: "user"
      ME_CONFIG_BASICAUTH_PASSWORD: "fairly long password"
      ME_CONFIG_MONGODB_ADMINUSERNAME: apibara
      ME_CONFIG_MONGODB_ADMINPASSWORD: apibara
    depends_on:
      - mongo

  apibara:
    # image: apibara/apibara:0.3.3
    image: apibara/starknet:ffbe469b2dadee8f5e3c11d35ee8b0f81915c63a
    restart: always
    command: apibara-starknet start --custom-network http://devnet:5050 # --config /usr/etc/apibara/configuration.toml
    ports:
      - 7171:7171
    environment:
      RUST_LOG: "apibara=debug"
      RUST_BACKTRACE: 1
    depends_on:
      - devnet
    # volumes:
    #   - ./apibara:/usr/etc/apibara

  devnet:
    image: shardlabs/starknet-devnet:latest
    ports:
      - 5050:5050
