# Page 1, Proposals
query Proposals {
  proposals(
    status: $status
    order_by: $order_by
    order_direction: $order_direction
  ) {
    id
    type
    title
    link
    submitted_at
    submitted_by
    description
    accepted_at
    processed_at
    majority
    quorum
    yes_votes
    no_votes
    current_majority
    current_quorum
    time_remaining
    voting_period_ending_at
    grace_period_ending_at

    ... on GuildKick {
      member_address
    }

    ... on OnBoard {
      address
      shares
      loot
    }

    ... on WhiteList {
      token_address
      token_name
    }

    ... on UnWhiteList {
      token_address
      token_name
    }

    ... on Swap {
      tribute_address
      tribute_offered
      payment_requested
      payment_requested
    }
  }
}

# Page 2, Proposal Page ? There is no such page but shouldn't it exist ?
query Page2 {
  proposal(id: $id) {
    id
  }
}

# Page 3, Monitoring
query Monitoring {
  # Can we use Authentification to automatically use the current user' address in the backend ?
  member(address: $address) {
    voting_power
    shares
  }
  members {
    address
    roles
    join_date
  }
  bank {
    total_shares # We can also make it a separate query/field
    token_balances {
      name
      amount
      price
      value
    }
    whitelisted_tokens {
      address
      name
    }
  }
}

# Page 4, Profile
query Profile {
  member(address: Address) {
    address
    roles
    delegate_key
    shares
    loot
    percentage_of_bank
    voting_power
    token_balances {
      address
      name
      amount
      price
      value
    }
  }
}
