proposals {
  {
    id
    type
    title
    link
    submittedAt
    submittedBy
    description
    acceptedAt
    processedAt
    majority
    quorum
    yesVotes
    noVotes
    currentMajority
    currentQuorum
    timeRemaining
    votingPeriodEndingAt
    gracePeriodEndingAt
  }
on guildkick {
        memberAddress
    }
on onboard {
        address
        shares
        loot
    }
on whitelist {
        tokenAddress
        tokenName
    }
on unWhitelist {
        tokenAddress
        tokenName
    }
on swap {
        tributeAddress
        tributeOffered
        paymentRequested
        paymentAddress
    }
}


members {
    address
    roles
}

bank {
    governance {
        totalLoots
        totalShares
        }
    balances {
        name
        amount
        price
        value
        }
    whitelistedTokens {
        address
        name
        }
}


profile {
    member (address: Address) {
        address
        roles
        delegateKey
        shares
        loot
        percentageOfBank
        votingWeight
        balances{
            address
            name
            amount
            price
            value
            }
        }
}
